- name: Set lightdm greeter
  lineinfile:
      path: /etc/lightdm/lightdm.conf
      insertafter: '^#greeter-session=example-gtk-gnome'
      line: greeter-session=lightdm-mini-greeter

- name: Enable greeter
  systemd:
      name: lightdm
      enabled: yes
