- name: Enable pipewire
  systemd:
      name: pipewire
      enabled: yes
      state: started
      scope: user

- name: Enable pipewire-pulse
  systemd:
      name: pipewire-pulse
      enabled: yes
      state: started
      scope: user
