---
quotes: "[`'\"]"
void: ""
ff_dir: [] # Firefox directory (e.g. ~/.mozilla/firefox/o2oqfi8r.default)

username: sammy

dotfiles_repo: https://github.com/galichenkosemyon/dotfiles.git
dotfiles_dir: "/home/{{ username|regex_replace(quotes, void) }}/dotfiles"

dotter_local: "{{ dotfiles_dir|regex_replace(quotes, void) }}/.dotter/local.toml"
dotter_local_packages: 'zsh", "tmux", "alacritty", "vim", "firefox", "herbstluftwm", "polybar", "rofi", "dunst", "picom", "vifm'

pacman_pkgs_system: [pacman-contrib, base-devel, xorg-server, lxappearance-gtk3, arc-gtk-theme, arc-icon-theme, lightdm]
pacman_pkgs_dev: [nodejs-lts-gallium]
pacman_pkgs_net: [networkmanager, nm-connection-editor, ntfs-3g, net-tools, bluez, bluez-utils, sshfs]
pacman_pkgs_sound: [pipewire, pipewire-pulse, wireplumber, mplayer]
pacman_pkgs_apps: [firefox, nemo, flameshot, signal-desktop, telegram-desktop, shotwell, krita, redshift, mpv, code, evince, discord, qutebrowser]
pacman_pkgs_utils: [nitrogen, stow, picom, yad, dunst, ueberzug, light-locker, zathura, zathura-pdf-poppler, feh, rofi, arandr]
pacman_pkgs_cli: [alacritty, pass, pass-otp, zsh, fzf, tmux, ripgrep, exa, bat, vifm, htop, flake8, shellcheck, xdotool, neofetch, kitty, rlwrap, dash, lsof, docker, duf, zoxide, glances, ipython, pyright, bash-language-server, lua-language-server, helix, entr, vidir]
pacman_pkgs_git: [git, git-lfs, lazygit]
pacman_pkgs_fonts: [adobe-source-han-sans-jp-fonts, adobe-source-han-serif-jp-fonts, fcitx5-im, fcitx5-configtool, fcitx5-mozc]

aur_pkgs_system: [herbstluftwm-git, lightdm-mini-greeter-git]
aur_pkgs_dev: [rust-nightly-bin]
aur_pkgs_sound: [spotify, nuclear-player-bin, spicetify-cli, spicetify-themes-git]
aur_pkgs_apps: [thunderbird-beta-bin]
aur_pkgs_utils: [polybar, rofi-dmenu, rofi-pass-git, libinput-gestures, packer, laptop-mode-tools]
aur_pkgs_cli: [neovim-nightly-bin, dotter-rs-bin, tealdeer, bottom-bin, dashbinsh, navi-bin]
