#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#2f3540'
nitrogen --restore &
picom -b
fcitx5 -d &
light-locker &

# remove all existing keybindings
hc keyunbind --all
setxkbmap -layout 'us,ru' -option 'grp:alt_shift_toggle,grp_led:scroll'

# keybindings
Mod=Mod4   # Use the super key as the main modifier
Alt=Mod1
Term=alacritty

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close

# Apps keybindings
hc keybind $Mod-Return spawn $Term
hc keybind $Mod-Ctrl-p spawn flameshot gui
hc keybind 0xff61 spawn flameshot full -c -p ~/Pictures/screenshots
#hc keybind $Mod-z spawn import -window "$(xdotool getwindowfocus)" ~/Pictures/screenshots/"$(date '+%Y%m%d-%H%M%S')".png
hc keybind 0xff7f spawn light-locker-command -l

# Rofi keybindings
hc keybind Ctrl-space spawn rofi -modi window,drun,ssh,file-browser,combi -show combi -combi-modi window,drun,ssh,file-browser -display-combi drun -async-pre-read
hc keybind Ctrl-Shift-space spawn rofi -modi file-browser -show file-browser
hc keybind $Alt-Ctrl-p spawn ~/.config/rofi/bin/passmenu.sh
hc keybind $Alt-Ctrl-r spawn ~/.config/rofi/bin/remmina.sh
hc keybind $Alt-Ctrl-t spawn rofi_trans
hc keybind $Alt-Ctrl-n spawn alacritty -t fzf-nova --class 'Flala' -o window.dimensions.columns=80 -o window.dimensions.lines=20 -o window.startup_mode=Windowed -e ~/bin/fzf/fzf-nova

# basic movement
# focusing clients
hc keybind Ctrl-Left  focus left
hc keybind Ctrl-Down  focus down
hc keybind Ctrl-Up    focus up
hc keybind Ctrl-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.01
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

#volume control
hc keybind 0x1008ff12 spawn ~/.config/polybar/scripts/i3vol mute
hc keybind 0x1008ff11 spawn ~/.config/polybar/scripts/i3vol down 5
hc keybind 0x1008ff13 spawn ~/.config/polybar/scripts/i3vol up 5
#backlight control
hc keybind 0x1008ff03 spawn xbacklight -dec 5 
hc keybind 0x1008ff02 spawn xbacklight -inc 5


# tags
tag_names=( {1..5} )
tag_keys=( {1..5} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-Right  use_index +1 --skip-visible
hc keybind $Mod-Left   use_index -1 --skip-visible
# cycle through tags while dragging along some window (e.g. Picture-in-Picture)
hc keybind $Mod-period spawn ~/.config/herbstluftwm/cycletag +1
hc keybind $Mod-comma  spawn ~/.config/herbstluftwm/cycletag -1

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#FFFFFF'
hc set frame_border_normal_color '#2f343f'
hc set frame_bg_normal_color '#2f343f'
hc set frame_bg_active_color '#FFFFFF'
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 10

hc attr theme.active.color '#FCBF49'
hc attr theme.normal.color '#FFFFFF'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 0
hc attr theme.floating.border_width 0
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#FCBF49'
hc attr theme.active.outer_color '#FCBF49'
hc attr theme.background_color '#2f3540'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 1
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

hc keybind $Mod-Shift-f attr clients.focus.floating toggle

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
# `xprop` to find out windowtype, class etc
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on # pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' floating=on focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class~'[Yy]ad' floating=on
#hc rule class~'[Tt]hunderbird' pseudotile=off floating=on #tag=3
hc rule class~'[Nn]m-connection-editor' pseudotile=off floating=on focus=on
hc rule class~'[Pp]avucontrol' pseudotile=off floating=on focus=on
hc rule instance~'Flala' pseudotile=off floating=on focus=on floatplacement=center
#hc rule class~'org.remmina.Remmina' pseudotile=off floating=on focus=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
#hc set_monitors 1920x1175+0+25 1920x1055+1920+25
#hc set_monitors 1920x1055+0+25
hc pad 0 25 0 0 0

# find the panel
#panel=~/.config/herbstluftwm/panel.sh
panel=$HOME/.config/polybar/launch.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done
